FROM python:3

WORKDIR /app/backend/src

# Copy requirements and install dependencies
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Copy only the contents of the src folder into the working directory
COPY src/ .

# Start the FastAPI app
CMD ["fastapi", "run", "main.py", "--host", "0.0.0.0", "--port", "80", "--reload"]
