name: messenger-v3

services:

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - frontend_build:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend

  frontend:
    container_name: frontend
    build:
      context: ../../frontend/frontend_app/
      dockerfile: Dockerfile.prod
    environment:
      - NODE_ENV=production
    volumes:
      - frontend_build:/app/dist

  backend:
    container_name: backend
    build: 
      context: ../../backend/
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
    environment:
      - USER_DATABASE_URL=postgresql://postgres:postgres@db:5432/messenger_db
      - CHAT_HISTORY_DATABASE_URL=mongodb://root:changeme@chat_history_db:27017
    depends_on:
      - db

  db:
    container_name: users_data_db
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=messenger_db
    ports:
      - "5435:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  chat_history_db:
    container_name: chat_history_db
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: changeme
    volumes:
      - mongo_data:/data/db

volumes:
  db_data:
  mongo_data:
  frontend_build:
